# feeder
feeder: feeders.feeder_uav.Feeder
train_feeder_args:
  data_path: /home/coop/quminghaonan/quminghaonan/dataset/data_prepro_info/MMVRAC_CSv2_sar_train_joint.npz
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 64
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: False
  bone: False

test_feeder_args:
  # data_path: /home/zjl_laoshi/xiaoke/UAV-SAR/data/uva_aug/MMVRAC_CSv2.npz
  # data_path: /home/coop/quminghaonan/quminghaonan/dataset/data_prepro_info/MMVRAC_CSv2_sar_train_joint.npz
  data_path: /home/coop/quminghaonan/quminghaonan/dataset/data_prepro_info/unaug/MMVRAC_CSv2_sar_test_joint.npz
  split: test
  window_size: 64
  p_interval: [0.95]
  vel: False
  bone: False
  debug: False

# model
model: model.ske_mixf.Model
model_args:
  num_class: 155
  num_point: 17
  num_person: 2
  graph: graph.uav.Graph
  graph_args:
    labeling_mode: 'spatial'
  k: 6

#optim
weight_decay: 0.0005
base_lr: 0.2
step: [35, 55, 75]
warm_up_epoch: 5

# training
device: 0
batch_size: 128
test_batch_size: 128
num_epoch: 90
nesterov: True
