run_mode: train

work_dir: /home/zjl_laoshi/xiaoke/UAV-SAR/sttformer/result/A/joint
# feeder
feeder: feeders.feeder_uav.Feeder
train_feeder_args:
  data_path: /home/coop/quminghaonan/quminghaonan/dataset/data_prepro_info/MMVRAC_CSv2_sar_train_joint.npz
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 120
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: False
  bone: False

test_feeder_args:
  # data_path: /home/coop/quminghaonan/quminghaonan/dataset/data_prepro_info/MMVRAC_CSv2_sar_train_joint.npz
  data_path: /home/coop/quminghaonan/quminghaonan/dataset/data_prepro_info/unaug/MMVRAC_CSv2_sar_test_joint.npz
  split: test
  debug: False
  window_size: 120
  p_interval: [0.95]
  vel: False
  bone: False

# model
model: model.sttformer.Model
model_args:
  len_parts: 6
  num_frames: 120
  num_joints: 17
  num_classes: 155
  num_heads: 3
  kernel_size: [3, 5]
  num_persons: 2
  num_channels: 3
  use_pes: True
  config: [[64,  64,  16], [64,  64,  16],
           [64,  128, 32], [128, 128, 32],
           [128, 256, 64], [256, 256, 64],
           [256, 256, 64], [256, 256, 64]]

#optim
weight_decay: 0.0004
base_lr: 0.1
lr_decay_rate: 0.1
step: [60, 80]
warm_up_epoch: 5

# training
device: 0
cuda_visible_device: '0,1,2,3,4,5,6,7'
batch_size: 32
test_batch_size: 32
num_epoch: 90
nesterov: True
