# feeder
feeder: feeders.feeder_uav.Feeder

# data_path: /home/coop/quminghaonan/quminghaonan/dataset/data_prepro_info/unaug/MMVRAC_CSv2_sar_train_joint.npz
data_path: /home/coop/quminghaonan/quminghaonan/dataset/data_prepro_info/unaug/MMVRAC_CSv2_sar_test_joint.npz
window_size: 64
random_rot: True
use_vel: False
use_angle: False

# model
num_class: 155
num_point: 17
num_person: 2
graph: graph.uav.Graph
k: 6
in_channels: 3
cl_mode: 'ST-Multi-Level'

#optim
weight_decay: 0.0005
base_lr: 0.1
step: [90, 100]
warm_up_epoch: 5

# training
device: 3
batch_size: 128
test_batch_size: 128
num_epoch: 130
nesterov: True

half: True